### ISSUE TITLE
human_state_name is not working on the initial state

### ISSUE THREAD

**Issue by vanboom** [state-machines/state_machines#76]
Consider this state machine configuration...
```ruby
class MyClass
  state_machine :state, initial: :pending do
    state :pending, human_name: "To Do"
    state :in_progress, human_name: "In Progress"
  end
end
```
Attempting to fetch the human state name...
```ruby
irb > MyClass.human_state_name :pending
=> "pending"
```

Other states work fine.  The initial state is not being translated.   Thanks.

**Comment by seuros** [comment]
```
irb(main):154:0> MyClass.human_state_name :pending
=> "To Do"
```

I could not reproduce it.

**Comment by rywall** [comment]
I also had this issue and it occurred specifically when I was using the Active Record adapter. The Active Record adapter overwrites the manually specified human name even if there are no translations specified in the i18n file. I solved it by specifying the translations in my `config/locales/en.yml` file instead of manually specifying the human state name.

**Comment by vanboom** [comment]
I think this is also related to `state_machines-mongoid` which appears to use `state_machines-active-model` - similar translation behavior vs. using the coded value.
